### ISSUE TITLE
Nebula Graph Studio 2.X   /api-nebula/db/exec 504 Gateway Time-out

### ISSUE THREAD

**Issue by shutter-cp** [vesoft-inc/nebula-studio#178]
使用Nebula Graph Studio 2.X   点击schema 504错误  504 Gateway Time-out
使用Nebula Graph Studio 1.X    正常

数据库Nebula Graph v2.0.0-beta 版本
![image](https://user-images.githubusercontent.com/37921589/101153981-1448ae80-3660-11eb-907d-6acf2163ee16.png)

![image](https://user-images.githubusercontent.com/37921589/101154137-49ed9780-3660-11eb-9eaa-80b4286e3e27.png)

**Comment by hetao92** [comment]
请问第一张图右上角 studio 版本是多少

**Comment by shutter-cp** [comment]
![image](https://user-images.githubusercontent.com/37921589/101157717-88d21c00-3665-11eb-94f8-064544d90da6.png)
v2.0.0-alpha

**Comment by shutter-cp** [comment]
就是使用2.0的studo 连graph2.0 点击schema报504了
使用老版本的studo 连graph2.0 正常

**Comment by hetao92** [comment]
studio 1.x 版本是不可能连接上 nebula 2.0 的，如果使用studio老版本(v1.2.1-beta)连接正常说明 graph 是 1.x 版本的。你要不要再确认一下。我刚刚本地用 nebula-docker-compose v2-preview分支上拉的 nebula2.0 镜像，和 nebula-web-docker v2目录下拉的 studio 2.0，是能正常打开并操作的，没有出现 504

**Comment by shutter-cp** [comment]
![image](https://user-images.githubusercontent.com/37921589/101167596-1d904600-3675-11eb-85c4-ac51b86a9dd4.png)

镜像是使用是dockerhub上的镜像
[graphd](https://hub.docker.com/layers/vesoft/nebula-graphd/v2.0.0-beta/images/sha256-e7fc51f02b9fada5a1335a24ae544db126929c3359a4d2502fd7c2a94430e8b4?context=explore)
[metad](https://hub.docker.com/layers/vesoft/nebula-metad/v2.0.0-beta/images/sha256-2e2f8c2b10b8c5f6b96d47ef1f235e10c45b2501c9d58b490b7db7cfe8b7e093?context=explore)
[storaged](https://hub.docker.com/layers/vesoft/nebula-storaged/v2.0.0-beta/images/sha256-2c896f594c65a123dcc9d82a44d916c5fe26487d8af3cfb3df55d6d97ae9d650?context=explore)

这个不是nebula2.0吗 我有没有什么办法确认版本

**Comment by nianiaJR** [comment]
你的studio和nebula是部署在远端的还是本地的？你要不用2.0的console连一下，验证下是否也会遇到同样的问题__

**Comment by shutter-cp** [comment]
都在远端，2.0的console没有问题。是不是你们放在dockerhub上面的  v2.0.0-beta 镜像不是最新的版本呀

**Comment by nianiaJR** [comment]
是最新版本，不过这个应该和最新版本无关。

如果都在远端的话，确定studio和nebula都在一个网络环境么？会不会有隔离的问题，要不你在本地启动下studio连接试试

**Comment by shutter-cp** [comment]
我试了试，自己编译的2.0.0bate版本 。使用dockerswam 方式部署 就会有504 getwaytimeout错误。
单独启一个镜像不会有这个问题

**Comment by nianiaJR** [comment]
这个问题还有么？

**Comment by shutter-cp** [comment]
修改 studio/nebula-web-docker/v2/docker-compose.yml
改为**restart: always**  即可，就不会出现这个问题，如果不改还是依旧的504 getwaytimeout

**Comment by shutter-cp** [comment]
```
version: '3.4'
services:
  client:
    image: vesoft/nebula-http-gateway:v2
    restart: always
    environment:
      USER: root
    ports:
      - 8080
    networks:
      - nebula-web
  web:
    image: vesoft/nebula-graph-studio:v2
    restart: always
    environment:
      USER: root
      UPLOAD_DIR: ${MAPPING_DOCKER_DIR}
    ports:
      - 7001
    depends_on:
      - client
    volumes:
      - ${UPLOAD_DIR}:${MAPPING_DOCKER_DIR}:rw
    networks:
      - nebula-web
  importer:
    image: vesoft/nebula-importer:latest
    restart: always
    networks:
      - nebula-web
    ports:
      - 5699
    volumes:
      - ${UPLOAD_DIR}:${MAPPING_DOCKER_DIR}:rw
    command:
      - "--port=5699"
      - "--callback=http://nginx:7001/api/import/finish"
  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nebula.conf
      - ${UPLOAD_DIR}:${MAPPING_DOCKER_DIR}:rw
    depends_on:
      - client
      - web
    networks:
      - nebula-web
    ports:
      - 7001:7001

networks:
  nebula-web:
```
