### ISSUE TITLE
Websocket Url is Empty 

### ISSUE THREAD

**Issue by alibek-sumup** [vesoft-inc/nebula-studio#584]
**Whenever we click on on schema or console tab, we are getting Websocket Url is empty and we cannot do anything further**

**We run nebula studio v3.7.0 with the latest nebula cluster and the latest nebula operator. We run all over k8s with ingress alb load balancer and the following ingress file
```
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "nebula-studio.name" . }}
  namespace: {{ .Values.namespace }}
  annotations:
    alb.ingress.kubernetes.io/success-codes: 200,404,301,302
    alb.ingress.kubernetes/listen-ports: '[{"HTTP": 80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.certPath }}
spec:
  ingressClassName: alb
  rules:
    - host: {{ .Values.nameOverride}}.{{ .Values.host }}.sam-app.ro # this needs to be using the cluster name
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "nebula-studio.name" . }}-service
                port:
                  number: {{ .Values.service.port }}
```
Also, we had used nginx but had the same error. 

1. Run Nebula Operator, Nebula Db and Nebula Studio over K8s
2. Login to Nebula Studio
3. Click on Schema or Console
4. `WebSocket URL is empty` - the error we are getting. 

**Expected behavior**
I expect that I can create graph schema and load data.
