### ISSUE TITLE
After executing a studio statement, there are display issues with the console.

### ISSUE THREAD

**Issue by QingZ11** [vesoft-inc/nebula-studio#650]
Nebula version 3.4, Nebula Studio version 3.7.

Currently, in Studio, there are cases where the executed statement is not displayed in the console.

![image](https://github.com/vesoft-inc/nebula-studio/assets/38887077/ff3bb7cd-af3b-4772-bacf-41ada9f1c3bf)

Additionally, there are cases where the execution result is not displayed, and the console does not provide any information. Ideally, there should be a timeout or other prompt in this situation.

ref: https://discuss.nebula-graph.com.cn/t/topic/14034

nebula 版本 3.4 nebula-studio 版本 3.7

现在 studio 遇到执行不出来的语句，可能存在控制台不展示该条被执行的语句；

![image](https://github.com/vesoft-inc/nebula-studio/assets/38887077/adeac84b-409d-42c5-8d9d-3945f59dfa23)

以及执行不出来结果，控制台没有返回任何信息，理论上这里应该报个 timeout 或者其他的提示信息；

**Comment by huaxiabuluo** [comment]
In previous versions, the server had a default timeout duration for WebSocket read and write operations, which could block corresponding coroutines when the returned data volume was too large, causing a heartbeat timeout and thus triggering the WebSocket's destruction logic. However, these anomalies were only reflected in the error logs, with no corresponding perception on the page. Therefore, we made the following adjustments:

- Exposed the WebSocket read and write parameter configuration

```yaml
WebSocket:
  # The maximum wait time (secend) for the pong message from peer.
  # If a peer does not respond to the ping message within this time, websocket connection will be closed.
  # default 60s, 0 means no limit
  WriteDeadline: 60
  # The maximum wait time (secend) for the ping message from peer.
  # If a peer does not send a ping message within this time, websocket connection will be closed.
  # default 60s, 0 means no limit
  ReadDeadline: 60
  # The maximum message size allowed from peer.
  # If a peer sends a message larger than this, an error will be thrown and websocket connection will be closed.
  # default: 64MB (32 * 1024 * 1024), 0 means no limit or system limit
  WriteLimit: 33554432
  # The maximum message size allowed from peer.
  # If a peer sends a message larger than this, websocket connection will be closed.
  # default: 8MB (8 * 1024 * 1024), 0 means no limit or system limit
  ReadLimit: 8388608
```

In situations where some queries return a very large volume of data, we can appropriately increase the values of `WriteDeadline`, `ReadDeadline`, and `WriteLimit` to avoid related execution anomalies.


- Threw WebSocket execution exception information to HTML page
